# Generated by Django 4.2.7 on 2023-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'birthday'), ('Wedding', 'wedding'), ('Anniversary', 'anniversay'), ('Business', 'business'), ('Other', 'other')], max_length=50),
        ),
    ]
