# Generated by Django 4.2.7 on 2023-12-16 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_order2_orderform_alter_orderform_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderForm',
        ),
    ]
