# Generated by Django 4.2.7 on 2023-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_orderform'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('request', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'OrdersForm',
            },
        ),
    ]
